version: '3.2'

services:
  nginx:
    restart: always
    volumes:
      - source: code
        target: /var/www/html
        type: volume
        volume:
          readonly: true

  php:
    restart: always
    volumes:
      - source: code
        target: /var/www/html
        type: volume
        volume:
          readonly: false

volumes:
  code:
    driver: local